# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: alimotta <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/03/19 16:30:56 by alimotta          #+#    #+#              #
#    Updated: 2023/03/19 16:51:03 by alimotta         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = rush-02

SRCS = main.c ft_atoi.c ft_print.c ft_find.c

FLAGS = -Wall -Wextra -Werror

all:	${NAME}

${NAME}:
	cc -o ${NAME} ${SRCS} -Iincludes ${FLAGS}

fclean:
	rm -f ${NAME}
